# Site settings
title: Abandoned
header-img: img/home-bg.jpg
copyright_name: midchildan
description: "For now..."
baseurl: ""
url: "http://blog.midchildan.org"
twitter_username: midchildan
github_username:  midchildan
# facebook_username:
# email_username:

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: post
            author: midchildan
            type: "post"

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "LICENSE"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jemoji]
